version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
            - v1-dependencies-{{ arch }}
      - run:
          name: Install dependencies
          command: npm install --prefer-offline
      - save_cache:
          key: v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      # - run:
      #     name: Start Selenium
      #     command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
      #     background: true
      - run:
          name: Install the latest Firefox ESR
          command: |
            sudo apt-get remove firefox-mozilla-build &&
            sudo apt install firefox-esr &&
            firefox --version
      - run:
          name: Run tests
          command: npm run nightwatch -e chrome
      - run:
          name: Run on browserstack
          command: npm run nightwatch -- -c nightwatch.browserstack.circleci.conf.js -e firefox

      - store_test_results:
          path: reports/
